services:
  profile_service_neo4j:
    container_name: profile_service_neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_server_memory_heap_max__size: "1024m"
    volumes:
      - "./.conf:/var/lib/neo4j/conf"