server:
  port: 8080
  servlet: 
    context-path: /identity
  
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_db"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: identity_service
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    org:
      springframework:
        security: DEBUG
